---
title: "Proposal"
output: html_document
---


# Names
Kaleb Wohlgemuth
Peter Cassioppi 
Karthikcharan Suresh 
Spencer Brown (Coordinator)
 
# Source
The dataset is from another class that two of the group members are in. It was scraped directly from Airbnb by the course' professor, Dr. Laura Ziegler. It can be found in csv format in the same repo as this file, at this link: https://github.com/spencerqbrown/ds202_project

# Dataset Overview
A random sample of 500 Airbnb listings from Chicago taken from all listings in Chicago from August 2008 to May 2017. The dataset contains attributes for each of the listings such as review scores, features of the listing (eg number of rooms, bathrooms, etc.), prices, location (coordinates, neighborhood), services provided (heat, wifi), rules (whether smoking or pets are allowed). 

# Background
AirBnB is a website that was founded in 2008 where users can list their homes or apartments for users to rent out by the night. AirBnB offers listings in more than 100,000 cities across the world, and 191 countries and regions. The company is a tech company, so there is a lot of data generated by their company each time a listing is made or a reservation is made. Recently, they have started offering “Experiences” which are activities or day trips listed on the website by users. 
https://news.airbnb.com/about-us/

# Plan for Exploratory Analysis
In this dataset, there are many different attributes of each listing that can be analyzed. We can compare the amount of beds, price, and other values of each home to get an idea of what homes listed on AirBnB in Chicago look like. 
We can also use some of the given data to predict the price for rooms based on the variables, and we can determine what attributes affect price the most. This can be used to give suggestions of prices to new listings, if the owner doesn’t know what value to price their listing at. We can also predict an expected rating based off different attributes and determine which attributes have the biggest effect on rating. 